### ISSUE TITLE
Not compatible with Imager Plugin

### ISSUE THREAD

**Issue by MattWilcox** [smcyr/Craft-FocusPoint#1]
The example code for using FocusPoint with Imager does not work.

`{% set image = entry.image.first() %}
{% set transformedImage = craft.imager.transformImage(image, {
    width: 800,
    height: 600,
    mode: 'crop',
    position: image.focusPctX ~ '% ' ~ image.focusPctY ~ '%'
})
<img src="{{ transformedImage.url }}">`

This was spitting out an "An unknown image object was used." Exception error. It is because Imager is checking for models that match either 'Craft\Imager_ImageModel' or 'Craft\AssetFileModel' - The actual model is 'Craft\FocusPoint_AssetFileModel'.

I've created a Pull Request with the fix for Imager; but there may be a better way?  https://github.com/aelvan/Imager-Craft/pull/31

**Comment by smcyr** [comment]
Thanks for the heads up, I didn't have time to actually test with Imager and thought it would work, but it seems I was wrong. I'll look into that when I have time, but yes, it seems like Imager would be the one needing a code update because the Focuspoint field type extends the asset field type.

**Comment by MattWilcox** [comment]
Would it be possible to rework the plugin so that it's just the co-ordinate fields that can be attached to any asset - leaving the image itself as a generic Craft image?

**Comment by MattWilcox** [comment]
FYI; there's another pull request on the Imager plugin that addresses the issue too - and more robustly - so hopefully Imager will be updated soon. https://github.com/aelvan/Imager-Craft/pull/29
