### ISSUE TITLE
Focuspoint with Eager Loading

### ISSUE THREAD

**Issue by SamLNL** [smcyr/Craft-FocusPoint#10]
Hi,

I'm using eager loading for retrieving some images for my gallery:

`{% set employments = craft.entries({
section: 'employments',
with: ['photo]
}) %}`

This works fine and I can see all images on my page.
But whenever I try to get the focuspoints of that image:

`photo[0].focusPctX` All images have the same focuspoints (50).

Whenever I try to retrieve the images without the Eager Loading function, it works fine.

Is this a known 'bug', or is Eager Loading just not supported by Focuspoint?

**Comment by smcyr** [comment]
Hello,

I'm not sure how to implement getEagerLoadingMap, if I debug the plugin, it doesn't even seem to go into that function. When I have time, I'll look more into it, but if you have more insight on that, it would be appreciated.

Thank you,

**Comment by aaronwaldon** [comment]
I know I'm a little late, but I was able to get eager loading to work with Focus Point by adding the following method in FocusPoint_AssetElementType.php:

```php
	/**
	 * Adds the focusX and focusY points to the row that populates the model. This
	 * allows the focus point to still work with eager loading.
	 * 
	 * @param DbCommand $query
	 * @param ElementCriteriaModel $criteria
	 */
	public function modifyElementsQuery(DbCommand $query, ElementCriteriaModel $criteria)
	{
		$query
			->addSelect('ff.focusX, ff.focusY')
			->leftJoin('focuspoint_focuspoints ff', 'ff.assetId = elements.id');

		parent::modifyElementsQuery($query, $criteria);
	}
```

Hope that helps!

**Comment by smcyr** [comment]
Thank you, it works great, I accepted your pull request !

**Comment by aaronwaldon** [comment]
Glad to help. Thank you for the great plugin! :)

**Comment by SamLNL** [comment]
Awesome!! Thanks!

**Comment by terryupton** [comment]
I am having issues with Eager Loading still. See these posts.
aelvan/Imager-Craft#168 (comment) and
#22

I am still trying to get to the bottom of it and understand exactly what is causing this to fallover, it seems as though it is getting a value from a previous asset or something?

Digging a little deeper into the database, I noticed two rows for the same asset.
10813	1988	31	0.07	0.17	1989	2018-04-26 20:24:39	2018-04-26 20:24:39	6bfbb940-d66e-418d-b211-6dfa6676acd3

5604	1988	9	0.01	-0.04	1989	2018-03-03 13:52:24	2018-03-03 13:52:24	f68806d6-e332-4881-b5ce-014fe2159571

I am wondering if with this fix, it is in-fact getting/selecting the wrong FocusPoint, where it has been used for a different field. Is there a way to extend this to match the right field ID?

I might be wrong in my assumption, but my PHP isn't strong enough to test or resolve.

Thanks.
