### ISSUE TITLE
Blank FocusPoint helper modal

### ISSUE THREAD

**Issue by stursby** [smcyr/Craft-FocusPoint#13]
After uploading an Asset and clicking the gear icon, nothing shows up in the FocusPoint helper modal. This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/527849/26810664/9208ffb4-4a32-11e7-9ccc-b0c679be23c5.png)

No JS `Console` errors, and using Craft `2.6.2981`.

Any thoughts? Hopefully I'm just missing something simple?

Using Plugin version `1.1.3`

![image](https://cloud.githubusercontent.com/assets/527849/26810707/cc5eba82-4a32-11e7-9f8d-c2cac2c16627.png)

**Comment by n-dw** [comment]
I had a similar Issue as well. I had to update my asset paths.
Originally was doing relative paths
site/

After checking the happylager site changed them to
{assetsBasePath}/site/
{assetsBaseUrl}/site/

**Comment by stursby** [comment]
@n-dw Thanks! Turns out the issue was I didn't had a Asset Public URL set... which is why I think the Focus Point plugin couldn't load the image.
