### ISSUE TITLE
Focuspoint coordinates gets reset

### ISSUE THREAD

**Issue by thaoms** [smcyr/Craft-FocusPoint#14]
When adding or removing a random (other types) field from my layout, all Focuspoint fields on that layout get reset.

**Comment by thaoms** [comment]
After some research:
This works fine in my localhost, the issue only shows on other environments.

It actually deletes the records from all focuspoint fields on that page.
When I delete this method, everything works ok.

https://github.com/smcyr/Craft-FocusPoint/blob/master/focuspoint/fieldtypes/FocusPoint_FocusPointFieldType.php#L76


So for some reason they don't get re-inserted in the database.

**Comment by brettburwell** [comment]
Hi there. My client also reported that the field is losing previously set focal points intermittently. It's the first I've heard of the issue, but like @thaoms reported, I've also edited other fields in the entry type's layout edit.

**Comment by smcyr** [comment]
Hi, I tried to add/delete fields on a layout with a focuspoint field and I didn't encounter the problem. Could you give me a specific example of a layout with fields where the problem arise please.
Thanks!
