### ISSUE TITLE
500 error when deleting Assets

### ISSUE THREAD

**Issue by m8brgarc** [smcyr/Craft-FocusPoint#19]
If I "Clear Imager Transforms" before deleting the Assets I get this error:

PHP Error [500]

Trying to get property of non-object (/var/www/craft/plugins/focuspoint/FocusPointPlugin.php:54)

I temporarily fixed it by checking for the element before doing the conditional on it's elementType:

```
$element = craft()->elements->getElementById($elementId);
                if($element) {
                    if ($element->elementType === "Asset") {
                        craft()->focusPoint_focusPoint->deleteFocusPointRecordsByAssetId($elementId);
                    } else {
                        craft()->focusPoint_focusPoint->deleteFocusPointRecordsBySourceId($elementId);
                    }
                }
```

**Comment by smcyr** [comment]
Thanks for bringing this up, it's fixed in the latest release.
