### ISSUE TITLE
Plugin version not updated

### ISSUE THREAD

**Issue by khalwat** [smcyr/Craft-FocusPoint#20]
The plugin version wasn't updated to `1.1.6`:

https://github.com/smcyr/Craft-FocusPoint/blob/master/focuspoint/FocusPointPlugin.php#L15

...while the changelog was:

https://github.com/smcyr/Craft-FocusPoint/blob/master/changelog.json

So the plugin will be seen as perpetually needing updating in the AdminCP

**Comment by smcyr** [comment]
thanks, it's fixed
