### ISSUE TITLE
Error when used as field in Neo

### ISSUE THREAD

**Issue by almeric** [smcyr/Craft-FocusPoint#4]
I'm getting the following error in the CP if i'm using your (awesome) plugin as a field in [Neo](https://github.com/benjamminf/craft-neo). 

`Trying to get property of non-object`  
**craft/plugins/focuspoint/fieldtypes/FocusPoint_FocusPointFieldType.php(26)**
```
14     public function getInputHtml($name, $criteria)
15     {
16         craft()->templates->includeJsResource('focuspoint/jquery.focuspoint.js');
17         craft()->templates->includeJsResource('focuspoint/jquery.focuspoint.helpertool.js');
18         craft()->templates->includeCssResource("focuspoint/focuspoint.css");
19         craft()->templates->includeCssResource("focuspoint/helper-tool.css");
20 
21         $id = craft()->templates->formatInputId($name);
22         $namespacedId = craft()->templates->namespaceInputId($id);
23 
24         $variables = $this->getInputTemplateVariables($name, $criteria);
25 
26         $db_attributes = craft()->focusPoint_focusPoint->getAllFocusPoints($this->model->id, $this->element->id);
27         $attributes = array();
28         foreach ($db_attributes as $db_attribute) {
29             $attributes[$db_attribute->assetId] = $db_attribute;
30         }
31 
32         $variables["focusAttributes"] = $attributes;
33         $variables["focusJs"] = "new Craft.FocusPointHelper(\"$namespacedId\");";
34 
35         return craft()->templates->render("focuspoint/input", $variables);
36     }
```

`$this->element` appears to be `null`. 

Not sure if this is an issue with this plugin or Neo though..

**Comment by smcyr** [comment]
Wow, the Neo plugin seems nice, I think I'll use it for my next projects. 
And it should be fixed, can you confirm it's working for you? 
Thanks for the nice words too :)

**Comment by almeric** [comment]
A colleague of mine started using Neo and he's pretty enthusiastic about it. I just started a new project with it so I can't say yet. First Neo matrix field I set up made me run into this problem :)

But the ability to re-use fields in is a big plus!

**Comment by almeric** [comment]
Didn't notice you'd already fixed it! Can confirm it's working now.

Thanks for the quick response
