### ISSUE TITLE
To complete the Focus Point update, some changes must be made to your database.

### ISSUE THREAD

**Issue by MattWilcox** [smcyr/Craft-FocusPoint#5]
Updated to 1.0.4 and I have had...

"To complete the Focus Point update, some changes must be made to your database."

at least eight times now. And the front end of the site is now...

"Service Unavailable
Our site is temporarily unavailable. Please try again later."

If I remove the new focuspoint folder and replace it with the old version the site works again.

**Comment by smcyr** [comment]
Sorry for that, I'm not sure why it's doing that, I'll look into it.
For now, you could delete the migrations folder in craft/plugins/focuspoint and it will stop trying to update.

**Comment by MattWilcox** [comment]
Thanks :)

**Comment by MattWilcox** [comment]
Hi,

this is leading to other issues - been onto the Craft guys about not being able to delete Assets and got this response:

> Here's the key line:
> 
> 2016/07/14 12:59:14 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wagtail`.`craft_focuspoint_focuspoints`, CONSTRAINT `craft_focuspoint_focuspoints_assetId_fk` FOREIGN KEY (`assetId`) REFERENCES `craft_assetfiles` (`id`)). The SQL statement executed was: DELETE FROM `craft_elements` WHERE `id`=:pUMCCy1YMG.
> You've got a plugin (FocusPoint) that has some inconsistent data in it with Craft's craft_assets table. That could be with a bug in the plugin or someone manually edited the table or any number other of reasons.

**Comment by smcyr** [comment]
Hi,

I fixed those two bugs with a new release (1.0.5). I was missing the "getSchemaVersion()", it's why it was updating everytime. Also, for the other bug, I added an event on asset delete to delete the focuspoint fields.

Thanks for the feedback and let me know if you encounter other bugs :)

**Comment by MattWilcox** [comment]
Awesome, thanks! That's now working correctly for me 👍
