### ISSUE TITLE
Focus Point part of Asset itself

### ISSUE THREAD

**Issue by spAnser** [smcyr/Craft-FocusPoint#8]
Is there a way to maybe have this as a field you add to an asset instead of being an asset field. Some images might always have the same focus point so it would be nice to integrate on a per image basis not a per image usage basis. Not sure exactly how it could work or if there is a way to do it without using a field on an asset. Unless you can create another default asset field on top of the ones already built in.

Use case:

If I use the same image on multiple pages. I also have to precisely click the exact same focus point so when imager resizes the image on both pages they end up with the same exact file name. Which only occurs if the focus point is 100% identical on both posts. Without a way of manually typing in the focus point and it being attached on a per usage basis this is slightly more difficult to do.

It is possible using the inspector and editing the hidden input fields but this is not something a client could be expected to do.

**Comment by smcyr** [comment]
Hey,

Someone else did it like you want it. The person used an asset based approach instead of my field approach. There you go:
https://github.com/roundhouse/focuspoint

**Comment by spAnser** [comment]
Thanks will take a look. I hope it has a cool preview like yours.
